local options = {
  "autoindent",
  "incsearch",
  "smartindent",
  "expandtab",
  "smarttab",
  "breakindent",
  "shiftwidth=2",
  "tabstop=2",
  "wrap",
  "autoread",
  "autowrite",
  "cursorline",
  "noshowcmd",
  "cmdheight=0",
  "backspace=start,eol,indent",
  "shiftround",
  "nobackup",
  "ignorecase",
  "signcolumn=yes",
  "linebreak",
  "number relativenumber",
  "clipboard+=",
  "laststatus=3",
  "termguicolors",
  "scrolloff=5",
  "title",
  "pumheight=10",
  "noswapfile",
  "noshowmode",
  "nowritebackup",
  "noruler",
  "foldexpr=nvim_treesitter#foldexpr()",
  "foldmethod=expr",
  "nofoldenable",
  "fillchars+=horiz:\\━",
  "fillchars+=horizup:\\┻",
  "fillchars+=horizdown:\\┳",
  "fillchars+=vert:\\┃",
  "fillchars+=vertleft:\\┫",
  "fillchars+=vertright:\\┣",
  "fillchars+=verthoriz:\\╋",
  "fillchars+=eob:\\ "
  -- "undofile",
}

for i, option in pairs(options) do
  vim.cmd("set "..option)
end
