local U = {}

U.dark_palette = {
	rosewater = "#f2d5cf",
	flamingo = "#eebebe",
	pink = "#f4b8e4",
	mauve = "#ca9ee6",
	red = "#e78284",
	maroon = "#ea999c",
	peach = "#ef9f76",
	yellow = "#e5c890",
	green = "#a6d189",
	teal = "#81c8be",
	sky = "#99d1db",
	sapphire = "#85c1dc",
	blue = "#8caaee",
	lavender = "#babbf1",
	text = "#c6d0f5",
	subtext1 = "#b5bfe2",
	subtext0 = "#a5adce",
	overlay2 = "#949cbb",
	overlay1 = "#838ba7",
	overlay0 = "#737994",
	surface2 = "#626880",
	surface1 = "#51576d",
	surface0 = "#414559",
	base = "#303446",
	mantle = "#292c3c",
	crust = "#232634",
}

U.light_palette = {
	rosewater = "#dc8a78",
	flamingo = "#dd7878",
	pink = "#ea76cb",
	mauve = "#8839ef",
	red = "#d20f39",
	maroon = "#e64553",
	peach = "#fe640b",
	yellow = "#df8e1d",
	green = "#40a02b",
	teal = "#179299",
	sky = "#04a5e5",
	sapphire = "#209fb5",
	blue = "#1e66f5",
	lavender = "#7287fd",
	text = "#4c4f69",
	subtext1 = "#5c5f77",
	subtext0 = "#6c6f85",
	overlay2 = "#7c7f93",
	overlay1 = "#8c8fa1",
	overlay0 = "#9ca0b0",
	surface2 = "#acb0be",
	surface1 = "#bcc0cc",
	surface0 = "#ccd0da",
	base = "#eff1f5",
	mantle = "#e6e9ef",
	crust = "#dce0e8",
}

U.terminal_dark_palette = {
  U.dark_palette.overlay0,
  U.dark_palette.red,
  U.dark_palette.green,
  U.dark_palette.yellow,
  U.dark_palette.blue,
  U.dark_palette.pink,
  U.dark_palette.sky,
  U.dark_palette.text,
  U.dark_palette.overlay1,
  U.dark_palette.red,
  U.dark_palette.green,
  U.dark_palette.yellow,
  U.dark_palette.blue,
  U.dark_palette.pink,
  U.dark_palette.sky,
  U.dark_palette.text,
}

U.terminal_light_palette = {
  U.light_palette.overlay0,
  U.light_palette.red,
  U.light_palette.green,
  U.light_palette.yellow,
  U.light_palette.blue,
  U.light_palette.pink,
  U.light_palette.sky,
  U.light_palette.text,
  U.light_palette.overlay1,
  U.light_palette.red,
  U.light_palette.green,
  U.light_palette.yellow,
  U.light_palette.blue,
  U.light_palette.pink,
  U.light_palette.sky,
  U.light_palette.text,
}
U.cmp_item_kind_highlights = {
  PmenuSel = { bg = "#282C34", fg = "NONE" },
  Pmenu = { fg = "#C5CDD9", bg = "#22252A" },

  CmpItemAbbrDeprecated = { fg = "#7E8294", bg = "NONE", strikethrough = true },
  CmpItemAbbrMatch = { fg = "#82AAFF", bg = "NONE", bold = true },
  CmpItemAbbrMatchFuzzy = { fg = "#82AAFF", bg = "NONE", bold = true },
  CmpItemMenu = { fg = "#C792EA", bg = "NONE", italic = true },

  CmpItemKindField = { fg = "#EED8DA", bg = "#B5585F" },
  CmpItemKindProperty = { fg = "#EED8DA", bg = "#B5585F" },
  CmpItemKindEvent = { fg = "#EED8DA", bg = "#B5585F" },

  CmpItemKindText = { fg = "#C3E88D", bg = "#9FBD73" },
  CmpItemKindEnum = { fg = "#C3E88D", bg = "#9FBD73" },
  CmpItemKindKeyword = { fg = "#C3E88D", bg = "#9FBD73" },

  CmpItemKindConstant = { fg = "#FFE082", bg = "#D4BB6C" },
  CmpItemKindConstructor = { fg = "#FFE082", bg = "#D4BB6C" },
  CmpItemKindReference = { fg = "#FFE082", bg = "#D4BB6C" },

  CmpItemKindFunction = { fg = "#EADFF0", bg = "#A377BF" },
  CmpItemKindStruct = { fg = "#EADFF0", bg = "#A377BF" },
  CmpItemKindClass = { fg = "#EADFF0", bg = "#A377BF" },
  CmpItemKindModule = { fg = "#EADFF0", bg = "#A377BF" },
  CmpItemKindOperator = { fg = "#EADFF0", bg = "#A377BF" },

  CmpItemKindVariable = { fg = "#C5CDD9", bg = "#7E8294" },
  CmpItemKindFile = { fg = "#C5CDD9", bg = "#7E8294" },

  CmpItemKindUnit = { fg = "#F5EBD9", bg = "#D4A959" },
  CmpItemKindSnippet = { fg = "#F5EBD9", bg = "#D4A959" },
  CmpItemKindFolder = { fg = "#F5EBD9", bg = "#D4A959" },

  CmpItemKindMethod = { fg = "#DDE5F5", bg = "#6C8ED4" },
  CmpItemKindValue = { fg = "#DDE5F5", bg = "#6C8ED4" },
  CmpItemKindEnumMember = { fg = "#DDE5F5", bg = "#6C8ED4" },

  CmpItemKindInterface = { fg = "#D8EEEB", bg = "#58B5A8" },
  CmpItemKindColor = { fg = "#D8EEEB", bg = "#58B5A8" },
  CmpItemKindTypeParameter = { fg = "#D8EEEB", bg = "#58B5A8" },
}

U.icons = {
  -- default_icon = { icon = "󰈚", name = "Default" },
  -- c = { icon = "", name = "c" },
  -- css = { icon = "", name = "css" },
  -- dart = { icon = "", name = "dart" },
  -- deb = { icon = "", name = "deb" },
  -- Dockerfile = { icon = "", name = "Dockerfile" },
  -- html = { icon = "", name = "html" },
  -- jpeg = { icon = "󰉏", name = "jpeg" },
  -- jpg = { icon = "󰉏", name = "jpg" },
  -- js = { icon = "󰌞", name = "js" },
  -- kt = { icon = "󱈙", name = "kt" },
  -- lock = { icon = "󰌾", name = "lock" },
  -- lua = { icon = "", name = "lua" },
  -- mp3 = { icon = "󰎆", name = "mp3" },
  -- mp4 = { icon = "", name = "mp4" },
  -- out = { icon = "", name = "out" },
  -- png = { icon = "󰉏", name = "png" },
  -- py = { icon = "", name = "py" },
  -- ["robots.txt"] = { icon = "󰚩", name = "robots" },
  -- toml = { icon = "", name = "toml" },
  -- ts = { icon = "󰛦", name = "ts" },
  -- ttf = { icon = "", name = "TrueTypeFont" },
  -- rb = { icon = "", name = "rb" },
  -- rpm = { icon = "", name = "rpm" },
  -- vue = { icon = "󰡄", name = "vue" },
  -- woff = { icon = "", name = "WebOpenFontFormat" },
  -- woff2 = { icon = "", name = "WebOpenFontFormat2" },
  -- xz = { icon = "", name = "xz" },
  -- zip = { icon = "", name = "zip" },
  java = { icon = "", color = "#e46368", name = "Java" },
  [".gitignore"] = { icon = "", color = "#428850", name = "GitIgnore" },
  js = { icon = "󰌞", color = "#f7cd6d", name = "JavaScript" },
  json = { icon = "", color = "#f7cd6d", name = "JSON" },
  ts = { icon = "󰛦", color = "#87b2e2", name = "TypeScript" },
  html = { icon = "", color = "#de7558", name = "Html" },
  rb = { icon = "", color = "#ef757c", name = "Rb" },
  rake = { icon = "", color = "#ef757c", name = "Rake" },
  rakefile = { icon = "", color = "#ef757c", name = "RakeFile" },
  jbuilder = { icon = "", color = "#f7cd6d", name = "Jbuilder" },
  lua = { icon = "", color = "#5166f0", name = "Lua" },
}

U.sign_icons = {
  add = '󰐖 ',
  change = '󱗜 ',
  delete = '󰅗 ',
  topdelete = '󰍵 ',
  changedelete = '󰇽 ',
  untracked = '󰐖 ',
  -- add = '󰐗 ',
  -- change = '󰻂 ',
  -- delete = '󰅙 ',
  -- topdelete = '󰍶 ',
  -- changedelete = '󰟃 ',
  -- untracked = '󰐗 ',

  -- success = '󰄳 ',
  -- info = '󰋼 ',
  -- error = '󰅙 ',
  -- hint = '󰋗 ',
  -- warning = '󰀨 ',
  warning_2 = ' ',
  warning_3 = '󰀨 ',

  info = '󰀧 ',
  warning = '󰬐 ',
  error = '󰅗 ',
  hint = '󰞋 ',
  success = '󰄲 ',
}

U.navic_icon = {
  File          = "󰈙",
  Module        = "",
  Namespace     = "󰌗",
  Package       = "",
  Class         = "󰌗",
  Method        = "󰆧",
  Property      = "",
  Field         = "",
  Constructor   = "",
  Enum          = "󰕘",
  Folder        = "󰉋",
  Interface     = "󰕘",
  Snippet       = "",
  Function      = "󰊕",
  Variable      = "󰆧",
  Constant      = "󰏿",
  String        = "󰀬",
  Number        = "󰎠",
  Text          = "󰉿",
  Keyword       = "󰌋",
  Boolean       = "◩",
  Copilot       = "",
  Codeium       = "",
  TabNine       = "",
  Array         = "󰅪",
  Object        = "󰅩",
  Key           = "󰌋",
  Null          = "󰟢",
  EnumMember    = "",
  Struct        = "󰌗",
  Event         = "",
  Operator      = "󰆕",
  TypeParameter = "󰊄",
}

U.nv_chad_icons = {
  Namespace     = "󰌗",
  Text          = "󰉿",
  Method        = "󰆧",
  Function      = "󰆧",
  Constructor   = "",
  Field         = "󰜢",
  Variable      = "󰀫",
  Class         = "󰠱",
  Interface     = "",
  Module        = "",
  Property      = "󰜢",
  Unit          = "󰑭",
  Value         = "󰎠",
  Enum          = "",
  Keyword       = "󰌋",
  Snippet       = "",
  Color         = "󰏘",
  File          = "󰈚",
  Reference     = "󰈇",
  Folder        = "󰉋",
  EnumMember    = "",
  Constant      = "󰏿",
  Struct        = "󰙅",
  Event         = "",
  Operator      = "󰆕",
  TypeParameter = "󰊄",
  Table         = "",
  Object        = "󰅩",
  Tag           = "",
  Array         = "[]",
  Boolean       = "",
  Number        = "",
  Null          = "󰟢",
  String        = "󰉿",
  Calendar      = "",
  Watch         = "󰥔",
  Package       = "",
  Copilot       = "",
  Codeium       = "",
  TabNine       = "",
}

U.local_icons = {
  Text          = "  ",
  Method        = "󰆧  ",
  Function      = "󰊕  ",
  Constructor   = "  ",
  Field         = "󰇽  ",
  Variable      = "󰂡  ",
  Class         = "󰠱  ",
  Interface     = "  ",
  Module        = "  ",
  Property      = "󰜢  ",
  Unit          = "  ",
  Value         = "󰎠  ",
  Enum          = "  ",
  Keyword       = "󰌋  ",
  Snippet       = "  ",
  Color         = "󰏘  ",
  File          = "󰈙  ",
  Reference     = "  ",
  Folder        = "󰉋  ",
  EnumMember    = "  ",
  Constant      = "󰏿  ",
  Array         = "[] ",
  Struct        = "  ",
  Event         = "  ",
  Operator      = "󰆕  ",
  TypeParameter = "󰅲  ",
  TabNine       = '󰂂  ',
  Copilot       = '  '
}

U.kind_icons = {
  Text          = '  ',
  Method        = '  ',
  Function      = '  ',
  Constructor   = '  ',
  Field         = '  ',
  Variable      = '  ',
  Class         = '  ',
  Interface     = '  ',
  Module        = '  ',
  Property      = '  ',
  Unit          = '  ',
  Value         = '  ',
  Enum          = '  ',
  Keyword       = '  ',
  Snippet       = '  ',
  Color         = '  ',
  File          = '  ',
  Reference     = '  ',
  Folder        = '  ',
  EnumMember    = '  ',
  Constant      = '  ',
  Struct        = '  ',
  Array         = "[] ",
  Event         = '  ',
  Operator      = '  ',
  TypeParameter = '  ',
  TabNine       = '󰂂  ',
  Copilot       = '  '
}

-- NOTE: Lsp server list
U.lsp_servers = {
  "tsserver",                        -- typescript
  "lua_ls",                          -- lua
  "cssls",                           -- css
  "jsonls",                          -- json
  "tailwindcss",                     -- tailwindcss
  "emmet_ls",                        -- emmet
  "html",                            -- html
  "solargraph",                      -- ruby
  "dockerls",                        -- docker
  "docker_compose_language_service", -- docker-compose
  "angularls",                       -- angular
  "eslint",                          -- eslint
  -- "vuels"
}

-- NOTE: Treesitter parser list
U.treesitter_parsers = {
  "lua",
  "javascript",
  "diff",
  "typescript",
  "json",
  "ruby",
  "html",
  "css",
  "scss",
  "angular",
  "bash",
  "dockerfile",
  "gitignore",
  "regex",
  "tsx",
  "vim",
  "vimdoc",
  "vue",
  "xml",
  "yaml",
  "markdown",
  "markdown_inline"
}

U.spinner_frames = { "⣾", "⣽", "⣻", "⢿", "⡿", "⣟", "⣯", "⣷" }
U.sbar           = { '▁', '▂', '▃', '▄', '▅', '▆', '▇', '█' }

U.border = vim.b.doc_border_type == "single" and {
  { "╭", "FloatBorder" },
  { "─", "FloatBorder" },
  { "╮", "FloatBorder" },
  { "│", "FloatBorder" },
  { "╯", "FloatBorder" },
  { "─", "FloatBorder" },
  { "╰", "FloatBorder" },
  { "│", "FloatBorder" },
} or vim.b.doc_border_type == "double" and {
  { "╔", "FloatBorder" },
  { "═", "FloatBorder" },
  { "╗", "FloatBorder" },
  { "║", "FloatBorder" },
  { "╝", "FloatBorder" },
  { "═", "FloatBorder" },
  { "╚", "FloatBorder" },
  { "║", "FloatBorder" },
} or vim.b.doc_border_type == "padding" and {
  { " ", "NormalFloat" },
  { " ", "NormalFloat" },
  { " ", "NormalFloat" },
  { " ", "NormalFloat" },
  { " ", "NormalFloat" },
  { " ", "NormalFloat" },
  { " ", "NormalFloat" },
  { " ", "NormalFloat" },
} or {
  { "", "" },
  { "", "" },
  { "", "" },
  { "", "" },
  { "", "" },
  { "", "" },
  { "", "" },
  { "", "" },
}

return U
